"init" support added
RedHatQE/cinch pull request #10
Opened 2017-01-12 22:22 UTC by robled

* Imported the entire 'os' module since it is used often and updated
references to it

* Fixed some outdated docstrings

* Moved inventory file validation checking and loading to a separate
function for readability

* Added a configuration skeleton for ease of use

* Elected to overwrite the example PinFile provided by linch-pin since
the example contains many sections that we do not use

* Improved error handling for topology files

2017-01-15 22:21 UTC, greg-hellings requested changes

2017-01-15 22:21 UTC, greg-hellings commented on cinch/bin/wrappers.py
> -from os import path, chdir, getcwd
Why'd you make this change?

2017-01-15 22:21 UTC, greg-hellings commented on cinch/bin/wrappers.py
> +
This method feels like it's complicated enough we should start thinking about factoring it out into some composing functions that just get selected based on if logic.

2017-01-15 22:21 UTC, greg-hellings commented on cinch/bin/wrappers.py
> +        skel_text = '''---
Do we have a standard for putting multi-line strings outside of the flow (e.g. as file globals)? If not, I propose that we do so, as these lines interrupt the normal flow of Python code. We could even factor them out into a separate file if we end up with multiple such strings.

2017-01-16 21:39 UTC, robled commented on cinch/bin/wrappers.py
> -from os import path, chdir, getcwd
Mainly for convenience.  As discussed we will leave it be and just import all of the 'os' module.

2017-01-16 21:40 UTC, robled commented on cinch/bin/wrappers.py
> +
The 'init' code has been moved into a separate function now.

2017-01-16 21:41 UTC, robled commented on cinch/bin/wrappers.py
> +        skel_text = '''---
These have been moved to the top of the file.

2017-01-17 22:31 UTC, merged