Introduce the option to add ssh keys to authorized_keys
RedHatQE/cinch pull request #103
Opened 2017-05-04 15:03 UTC by jpaulovic

Possibly related to #22 .

2017-05-04 16:00 UTC, robled requested changes

2017-05-04 16:00 UTC, robled commented on cinch/roles/jenkins_common/tasks/main.yml
> +- name: add ssh keys to authorized_keys
Let's add "for the jenkins user" to the name of this task so in log output it's a bit more clear what this is doing.

2017-05-04 16:33 UTC, greg-hellings commented on cinch/roles/jenkins_common/defaults/main.yml
> +# Set the default (empty) set of authorized keys for jenkins user.
You might want to add a note that this should be an array of file names on the local path pointing to public keys, so someone doesn't try to add the key values directly into this array or blindly add private keys or some other such nonsense.

2017-05-08 14:40 UTC, robled commented on cinch/roles/jenkins_common/defaults/main.yml
> +# in the local path pointing to separate public keys.
Can the given path be relative or is a full path required?  I find that sometimes Ansible needs a full path in certain environments, and we should always document whether a relative or full path is acceptable.

2017-05-08 15:34 UTC, jpaulovic commented on cinch/roles/jenkins_common/defaults/main.yml
> +# in the local path pointing to separate public keys.
Both relative and full paths work. I updated the wording to state that.

2017-05-08 15:42 UTC, robled approved these changes

2017-05-08 20:57 UTC, jpaulovic commented on cinch/roles/jenkins_common/defaults/main.yml
> +# Set the default (empty) set of authorized keys for jenkins user.
Documentation updated.

2017-05-09 11:15 UTC, merged