Added error reporting for swarm service failures via systemd and upstart
RedHatQE/cinch pull request #107
Opened 2017-05-08 21:37 UTC by robled

* Modified service templates to allow the init system to manage swarm's
retry behavior

* Ansible will now fail if the swarm client cannot connect to the
master, and will pretty-print the error message for human consumption.

* Service timeouts and retry delays have been set to 10 seconds to align
with the default behavior of the swarm client.

* Re-ordered lines in service templates to make them easier to compare
side-by-side

* Fixed an issue in the upstart service template where the
authentication parameters were not set

2017-05-10 20:01 UTC, tehsmyers approved these changes
LGTM, but my ansible-fu isn't strong enough to say if there's a better option than the conditional includes, so another ack might be good. The comments make some of the eyebrow-raisers make sense, so thanks for those.

2017-05-10 20:01 UTC, seandst commented
As far as I can tell, the travis failure is environmental, related to f25 having trouble updating with yum.

2017-05-10 20:17 UTC, jpaulovic commented on cinch/roles/jenkins_slave/templates/swarm.service
> +          -retry 0 \
are you sure you want to limit it so strictly? Wouldn't at least one retry make sense here?

2017-05-10 20:26 UTC, greg-hellings requested changes

2017-05-10 20:26 UTC, greg-hellings commented on cinch/roles/jenkins_slave/tasks/check_swarm_systemd.yml
> +  shell: >
Mmm, shell magic. <3

2017-05-10 20:26 UTC, greg-hellings commented on cinch/roles/jenkins_slave/tasks/check_swarm_systemd.yml
> +  ignore_errors: yes
Can we go with "true" here, instead of "yes"? The rest of the codebase sticks with true/false instead of yes/no.

2017-05-10 20:26 UTC, greg-hellings commented on cinch/roles/jenkins_slave/tasks/check_swarm_upstart.yml
> +- name: check if swarm connected to the master with upstart
Does upstart not provide us the niceties that systemd offers?

2017-05-10 20:26 UTC, greg-hellings commented on cinch/roles/jenkins_slave/templates/swarm.service
> +# Wait 10 seconds (swarm client default) for the service to fail; code in
If code elsewhere depends on this, and we want it to match in these two locations, should we pull it out to a single variable so we don't rely on a magic value?

2017-05-10 20:50 UTC, robled commented on cinch/roles/jenkins_slave/tasks/check_swarm_systemd.yml
> +  ignore_errors: yes
I missed some consistency here.  Will fix.

2017-05-10 20:51 UTC, robled commented on cinch/roles/jenkins_slave/tasks/check_swarm_systemd.yml
> +  shell: >
After reading some systemctl and journalctl docs it was the only way I could find to grab the *last* log output of the swarm service.

2017-05-10 20:54 UTC, robled commented on cinch/roles/jenkins_slave/tasks/check_swarm_upstart.yml
> +- name: check if swarm connected to the master with upstart
Based on my research it does not, unfortunately.  systemd is way more feature-rich than upstart.  upstart's log/status functionality leaves much to be desired, and if you run 'initctl status swarm' you'll get a zero exit code back even though the state is anything but *OK*.

2017-05-10 20:54 UTC, robled commented on cinch/roles/jenkins_slave/templates/swarm.service
> +# Wait 10 seconds (swarm client default) for the service to fail; code in
Good catch, I'll see about getting this added.

2017-05-15 13:12 UTC, greg-hellings approved these changes

2017-05-16 14:51 UTC, merged