Install additional pip packages on Jenkins master
RedHatQE/cinch pull request #122
Opened 2017-06-01 14:01 UTC by jpaulovic

2017-06-05 21:03 UTC, robled approved these changes

2017-06-05 21:12 UTC, greg-hellings requested changes
I'd like to avoid installing anything further through pip at the global namespace, please?

2017-06-05 23:17 UTC, robled commented
Certainly I agree with @greg-hellings with regards to installing things from **pip** system-wide, but having this option is nice for those times when something just isn't packaged for a distro and using a virtualenv is somehow not desired.  Is there a specific use case we are accounting for?

2017-06-06 16:19 UTC, robled commented
Per a recent meeting we've decided to not include this feature in cinch, as we don't currently have a use case for it.  In the event that a use case develops (or returns), then we can resurrect this PR.

2017-06-06 16:19 UTC, closed without merging