roles/ntp: add support for configurable ntp servers
RedHatQE/cinch pull request #137
Opened 2017-07-17 21:54 UTC by scottlinux

- New `ntp_servers` override to specify optionally desired ntp server config.

- Example and brief note in group_vars/all

- If `ntp_servers` is not defined, distro defaults are used.

For https://github.com/RedHatQE/cinch/issues/135

2017-07-21 16:29 UTC, greg-hellings requested changes
Can we get a comment in the ChangeLog for this? That file was added after 0.7.0 was released and little updates like this would be nice to include there for release-time publication.

2017-07-22 00:40 UTC, scottlinux commented
Ok thanks - I'll update the PR with a ChangeLog bit added.

2017-07-25 13:26 UTC, scottlinux commented
Comment added in Change log

2017-07-25 14:33 UTC, greg-hellings submitted a review, later dismissed

2017-07-26 16:18 UTC, robled approved these changes

2017-07-26 16:18 UTC, merged