Make jenkins_user_api.py more robust
RedHatQE/cinch pull request #179
Opened 2017-09-16 05:00 UTC by greg-hellings

The jenkins_user_api module was not properly capturing errors and
incorrect exit codes when the module was being executed improperly. Now,
more of those cases should be handled properly and trigger an error
state in Ansible.

Fixes: #151

2017-09-19 16:22 UTC, robled requested changes

2017-09-19 16:22 UTC, robled commented on cinch/library/jenkins_user_api.py
> +        # If err and output are some type of empty, but not the empty string
Let's expand this comment to further explain the conditions that we're trying to catch here.

2017-09-21 13:14 UTC, robled submitted a review, later dismissed

2017-09-21 13:17 UTC, greg-hellings commented
Fixing the merge conflict in CHANGELOG dismissed your approval.

2017-09-21 13:30 UTC, robled approved these changes

2017-09-21 13:39 UTC, merged