Auto deploy
RedHatQE/cinch pull request #75
Opened 2017-04-14 04:25 UTC by greg-hellings

This *should* result in code that auto-deploys to PyPI and Docker Hub when a tag is pushed to GitHub.

2017-04-17 15:04 UTC, robled requested changes

2017-04-17 15:04 UTC, robled commented on scripts/deploy.sh
> +#!/bin/bash -e
Wrap this code at 80 characters.

2017-04-17 21:20 UTC, robled approved these changes

2017-04-17 22:46 UTC, robled commented
This patch is approved, but I'm not merging it myself since it contains release automation bits and it's probably best if the submitter merges it since they have a better understanding of how merging it could affect any triggers or automation that would result.

2017-04-18 03:15 UTC, greg-hellings commented
Merging now. Just having the code in the branch /shouldn't/ mess anything up. The deploy code should only activate when a tag is pushed, which I'll do in a second, after this merge.

2017-04-18 03:15 UTC, merged